name: Monitor Replit

on:
  push:
    branches: [ "master" ]

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Replit Status
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://replit.com/@rizalzall/delta-neww#LICENSE || exit 1
