name: Deploy to Server

on:
  push:
    branches:
      - master  # Ganti dengan nama branch yang sesuai jika perlu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ganti dengan versi Node.js yang sesuai

      - name: Install dependencies
        run: npm install


      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          sshpass -p '12345678900' ssh -o StrictHostKeyChecking=no root@188.75.79.75 -p 22 << 'EOF'
            cd /path/to/deploy
            npm install
            pm2 restart app
          EOF
